### ISSUE TITLE
High scores

### ISSUE THREAD

**Issue by Yoric** [Yoric/piranhas#11]
- Display the highest score close to the score.
- Store it using Indexed DB.
- Reload it from Indexed DB.

**Comment by toukeuz** [comment]
Je prend cette feature.

**Comment by Yoric** [comment]
Assigned to @toukeuz

**Comment by Yoric** [comment]
In the absence of any news, I had to implement this feature myself. This is very disappointing.
Not mentioning that you have abandoned a feature is a very bad idea, @toukeuz.

**Comment by toukeuz** [comment]
Malgré les cours et l'aide de Laurent Jouaneau, je n'ai pas réussi à faire fonctionner IndexedDB sur mon poste. Il m'était donc impossible de réaliser la feature ...

**Comment by Yoric** [comment]
Là n'est pas le problème. Échouer est quelque chose qui peut arriver. Laissé tomber une tâche qui vous était confiée sans prévenir, par contre, c'est inadmissible.

Au demeurant, malgré mon insistance, je ne vous ai pas vu sur IRC venir poser des questions aux personnes qui pouvaient vous aider. Dans le domaine du Logiciel Libre, ne pas demander de l'aide quand on a un problème n'est pas non plus acceptable.
