### ISSUE TITLE
Port to Canvas

### ISSUE THREAD

**Issue by Yoric** [Yoric/piranhas#12]
Currently, the game is not very smooth. This is largely because it uses DOM rather than Canvas. To make it faster, we should port it to Canvas.

**Comment by Yoric** [comment]
@AntSoft, you mentioned that you were interested in this bug. How's it going?

**Comment by anthony-trpc** [comment]
Hi, for now i working in this bug again

**Comment by Yoric** [comment]
Any news?

**Comment by Yoric** [comment]
@AntSoft, we will need this feature soon.

**Comment by Yoric** [comment]
Well, I've done it.

**Comment by Yoric** [comment]
@AntSoft, if you evere give up on an issue, please have the decency to inform the project owner.

Issue fixed by b3201d6ce6
