### ISSUE TITLE
Add an "infinite" mode

### ISSUE THREAD

**Issue by Yoric** [Yoric/piranhas#15]
It would be fun to have a mode "infinite", in which piranhas are spawned continuously (probably with an upper limit to the number of piranhas on screen).

**Comment by Yoric** [comment]
Assigned to @kbrivois, @jbarbin, @aratogobal.

**Comment by Yoric** [comment]
Guys, any news?

**Comment by kbrivois** [comment]
Désolé, je n'ai pas pu travailler dessus en ce moment. Rappelez moi ce qu'on avait convenu, les piranhas devaient apparaitre à 1/4 de la taille du terrain de distance autour du sombrero c'est ça ?

**Comment by Yoric** [comment]
Either that or from the opposite border. Regardless, the best way to do this is to have a (working) patch quickly so that we may iterate.

**Comment by Yoric** [comment]
@kbrivois, @jbarbin, we will need that feature soon

**Comment by Yoric** [comment]
@kbrivois, @jbarbin, I had to implement this feature myself. This is quite disappointing. 

Fixed by 1aaa9534b3 and ed517fc23f.
