### ISSUE TITLE
Pause the game when the user changes tab/app

### ISSUE THREAD

**Issue by Yoric** [Yoric/piranhas#18]
More details about the API: https://developer.mozilla.org/en-US/docs/DOM/Using_the_Page_Visibility_API

**Comment by yacir** [comment]
I would like to add this feature.

**Comment by Yoric** [comment]
Assigned to @yacir

**Comment by Moloss** [comment]
I have another code for this feature. Can I send this?

**Comment by Yoric** [comment]
Nope, the bug is assigned to @yacir.
