### ISSUE TITLE
Add licensing information

### ISSUE THREAD

**Issue by Yoric** [Yoric/piranhas#2]
To comply with open-source guidelines, this project should contain:
- a file `LICENSE` with the license;
- a header in each source file with t

The license for this project is the following: http://www.mozilla.org/MPL/headers/ .

Also, the license for any image or sound should also be added.

**Comment by Newyn** [comment]
I would like to take it

**Comment by Yoric** [comment]
Assigned to @vtriquet .

**Comment by Yoric** [comment]
Done, thanks for the contribution
