### ISSUE TITLE
Improve collision detection

### ISSUE THREAD

**Issue by Yoric** [Yoric/piranhas#23]
The current implementation of collision detection will not scale up to 100 piranhas. This is a shame. Let's fix it.

**Comment by Futa09** [comment]
I don't know if it's the right place, but i can provide a little less harsh collision, so we can may be increase the number of piranhas.

**Comment by Yoric** [comment]
That's a different bug. File it and I will assign it to you.

**Comment by Yoric** [comment]
Assigned to @Yoric
