### ISSUE TITLE
Regroup sprites in a single file

### ISSUE THREAD

**Issue by Yoric** [Yoric/piranhas#24]
At the moment, we have one file for piranhas, one for the sombrero. We can easily regroup them in a single [_sprite sheet_](http://css-tricks.com/css-sprites/) which would make downloads faster and save overall space.

**Comment by AAymeric** [comment]
Ok i take !

**Comment by Yoric** [comment]
Assigned to @AAymeric

**Comment by Yoric** [comment]
Fixed, thanks.
