### ISSUE TITLE
Making collision less hard

### ISSUE THREAD

**Issue by Futa09** [Yoric/piranhas#28]
The collision right now can affect the gameplay of player so by making the collision less harsh more people can enjoys it

**Comment by Yoric** [comment]
Assigned to @Futa09

**Comment by Yoric** [comment]
At the moment, we decide that two sprites are in collision if their bounding rectangles have at least one pixel in common. One way to make it less harsh is to decide that two sprites are in collision if their bounding rectangles have at least 3x3 pixels in common, for instance.

**Comment by Yoric** [comment]
Fixed, thanks.
