### ISSUE TITLE
Increase speed progressively

### ISSUE THREAD

**Issue by Yoric** [Yoric/piranhas#57]
To keep things interesting, speed should increase with the score.

**Comment by nourhane** [comment]
i want to solve this work

**Comment by Yoric** [comment]
Assigned to @nourhane

**Comment by Yoric** [comment]
Any progress, @nourhane?

**Comment by Yoric** [comment]
@nourhane, we will need this feature soon

**Comment by Yoric** [comment]
Well, I had to do it myself. I am very disappointed, @nourhane, not only because you have abandonned this feature, but also because you have failed to mention it.

Fixed by 97a4df905f
