### ISSUE TITLE
Add bonus points for killing piranhas

### ISSUE THREAD

**Issue by Yoric** [Yoric/piranhas#60]
At each frame:
- 100 points for the first piranha that dies;
- 100 points for the second;
- 200 points for the third;
- 400 points for the fourth;
- 800 points for the fifth;
- ...

**Comment by virginieseck** [comment]
I want to work on this bug. 
best regards.

**Comment by Yoric** [comment]
With great pleasure.
Assigned to @virginieseck .

**Comment by Yoric** [comment]
Any news of this feature, @virginieseck?

**Comment by Yoric** [comment]
@virginieseck, we will need this feature soon

**Comment by Yoric** [comment]
I had to do this myself. @virginieseck, I am disappointed. You have abandonned a work in progress without informing anyone. This is not acceptable.
